
current_balances:
  checking_1     : $8,000.00
  savings_1      : $24,000.00
  edu_savings    : $12,000.00
  monthly_cache  : $1,500.00
  paypal         : $600.00
  credit_1       : -$450.00
  credit_2       : -$200.00

format:
#  account:
#    columns:  [date_column, description_column, amount_column]
#    row_order: (ascending, descending), default 'descending'
#    date_format: default '%Y-%m-%d'
#    trans_type: column that denotes 'credit' or 'debit' (when to change the amount to negative)
#    rules: [ [ haystack, # column to search (not necessarily description)
#               needle,   # regex used to search the column,
#               action ],  # what to do if regex search matches (include|exclude)
#              ...]

  checking_1:
    columns: [0,1,3]

  savings_1:
    columns: [0,1,3]

  edu_savings:
    columns: [1,4,2]

  monthly_cache:
    columns: [0,4,1]
    rules:
      - [4, 'paypal', 'exclude']
    date_format: '%m/%d/%Y'

  paypal:
    columns: [0,3,7]
    date_format: '%m/%d/%Y'
    rules:
      - [4, 'ayment', 'include']
    order: 'ascending'

  credit_1:
    columns: [0,2,4]
    date_format: '%m/%d/%Y'
    trans_type: 3

  credit_2:
    columns: [0,2,4]

